import type { Metadata } from "next";
import { Karla } from "next/font/google";
import "./styles/globals.css";

import Navigacija from "./components/navigacija/navigacijs";
import Animacija from "./components/ui/animacija";

const karla = Karla({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-karla",
});

export const metadata: Metadata = {
  title: "Peplink užduotis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${karla.variable} antialiased`}>
        {/* animacija užkranant puslapi */}
        <Animacija>
          {/* navigacija */}
          <Navigacija />

          {children}
        </Animacija>
      </body>
    </html>
  );
}
